apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/user1-tenant/appstudio/dc-metro-map@sha256:c023b891823384fd89f2065edb275db664059f1ede0a996ff1683a2d03b6fc7e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
